[project]
name = "booking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]


[tool.ruff.format]
quote-style = "single"